In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
file_path='X:\hemlo\car_price_prediction.csv'
data=pd.read_csv(file_path)
columns_irrelevant=['ID','Model','Levy','Wheel','Color','Leather interior']
data_filtered = data.drop(columns=columns_irrelevant)
columns_to_encode = ['Gear box type', 'Fuel type', 'Manufacturer', 'Category', 'Drive wheels','Doors']
data_encoded = pd.get_dummies(data_filtered, columns=columns_to_encode)
data_encoded.head()

,Price,Prod. year,Engine volume,Mileage,Cylinders,Airbags,Gear box type_Automatic,Gear box type_Manual,Gear box type_Tiptronic,Gear box type_Variator,...,Category_Minivan,Category_Pickup,Category_Sedan,Category_Universal,Drive wheels_4x4,Drive wheels_Front,Drive wheels_Rear,Doors_02-Mar,Doors_04-May,Doors_>5
0,13328,2010,3.5,186005 km,6.0,12,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False
1,16621,2011,3,192000 km,6.0,8,False,False,True,False,...,False,False,False,False,True,False,False,False,True,False
2,8467,2006,1.3,200000 km,4.0,2,False,False,False,True,...,False,False,False,False,False,True,False,False,True,False
3,3607,2011,2.5,168966 km,4.0,0,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False
4,11726,2014,1.3,91901 km,4.0,4,True,False,False,False,...,False,False,False,False,False,True,False,False,True,False